spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/benion_store_api?createDatabaseIfNotExist=true
    username: root
    password: rice8828
  jpa:
    show-sql: true